// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCddFlWvPTlLcwnGRkdV0eSbgRwXWdQrA',
    appId: '1:1059243169233:android:5121ebe07302ab526cfcf0',
    messagingSenderId: '1059243169233',
    projectId: 'analytics-581d7',
    storageBucket: 'analytics-581d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0GxgLAbxEf92sVZ1vSEpKB39gwkROoI',
    appId: '1:1059243169233:ios:aff34a8df1daa8ac6cfcf0',
    messagingSenderId: '1059243169233',
    projectId: 'analytics-581d7',
    storageBucket: 'analytics-581d7.appspot.com',
    iosBundleId: 'net.redeemx.patron.samplefire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0GxgLAbxEf92sVZ1vSEpKB39gwkROoI',
    appId: '1:1059243169233:ios:cf39aa2555367f3f6cfcf0',
    messagingSenderId: '1059243169233',
    projectId: 'analytics-581d7',
    storageBucket: 'analytics-581d7.appspot.com',
    iosBundleId: 'net.redeemx.patron.samplefire.RunnerTests',
  );
}
